### PR TITLE
New naming

### PR DESCRIPTION
**Pull request by csshugs**
As per inuitcss/trumps.spacing#8

### CODE REVIEW

**Comment by lucasmotta** [comment]
:+1:

**Comment by zomars** [comment]
Can you put it on bower with your custom namespace so I can install it?

**Comment by csshugs** [comment]
@zomars You can install it via:

```
$ bower install https://github.com/csshugs/trumps.spacing-responsive.git#new-naming
```

This refers to the latest state of this pull-request (the branch `new-naming` of my fork from [trumps.spacing-responsive](https://github.com/inuitcss/trumps.spacing-responsive))

**Comment by zomars** [comment]
Thank you!

**Comment by tibastral** [comment]
+1

**Comment by fsmanuel** [comment]
:+1:

**Comment by anselmh** [comment]
Since this will break compatibility of the module with previous versions, we won’t integrate this before the next major version of inuitcss, sorry. 
Therefore while appreciating your proposal, I’ll close this now.

**Pull request closed without merging**
